### ISSUE TITLE
Bulk install and update from the plugin-install screen

### ISSUE THREAD

**Issue by adamsilverstein** [obenland/shiny-updates#10]
Making some progress on this, so far i have preliminary versions of selection and bulk updating:

http://cl.ly/090s2Z070U3g/Screen%20Recording%202015-12-24%20at%2012.37%20PM.gif

**Comment by adamsilverstein** [comment]
Bulk plugin instals first pass in develop. https://github.com/obenland/shiny-updates/commit/22eefacc6db0a3842290167aa861e2f3a01d421d

**Comment by adamsilverstein** [comment]
Here is how it looks so far:

![screencast](http://cl.ly/2y1v0F0H430d/Screen%20Recording%202015-12-25%20at%2003.27%20PM.gif)

**Comment by paaljoachim** [comment]
This looks really nice Adam!

**Comment by adamsilverstein** [comment]
Thanks @paaljoachim - I'm not sure it will make it into the plugin, we are discussing as a group... if it doesn't, I'll consider wrapping it up into a separate plugin.

**Comment by paaljoachim** [comment]
Well that might be because the bulk button is so highly visible. It would be less visible if one could do a bulk install through favorites (probably the most natural place to have it since one has a list of favorite plugins in there). The point is that having bulk install would make things a lot easier. This way or that way. Happy New Year! We are just into the new year here in Norway..:)

**Comment by j-falk** [comment]
Hi @adamsilverstein, thanks for this! One thought about the bulk process, is there really a need for a separate bulk button and that extra click?

Wouldn't a more preferred workflow be to able to install/update multiple plugins by clicking multiple install/update buttons and that they then get queued without having to enable the bulk mode?

Almost working already:
![untitled gif](https://cloud.githubusercontent.com/assets/1665833/12070249/8fbd13dc-b067-11e5-8e05-cc04465c90d6.gif)

But would probably benefit from getting a notification triggered showing how many installs/updates that have been queued so that is easy to follow and then the possibility to easily cancel an install/update if you change your mind.

Would be great if you even could continue searching for additional plugins after you initiated a install/update or maybe leave the plugin admin section at all and maybe start configuring a plugin while additional plugins are being updated/installed, but maybe that is a too complicated thing to accomplish?

I guess the benefit of a bulk-mode/button would be that you could review all install/updates before you initiate it, sort of like a shopping basket before placing a an order, but like I said I would probably rather want to be able to install/update continuously without having to enable such a mode.

**Comment by paaljoachim** [comment]
Going to installed plugins clicking update the spinner turns and then one sees the checkmark and the word updated. Doing something similar for installing plugins would also be very nice.
As clicking to install with updating and installed as you show it j-falk one can also easily jump to multiple plugins and install them as well. It is a natural shiny update progression. Bringing it to the new install procedure.

**Comment by adamsilverstein** [comment]
@j-falk I think you are right, we may not need a bulk mode. I think you can already queue up multiple updates and installs with the buttons, not using the bulk mode. Did this work for you or did you see any issues?

**Comment by j-falk** [comment]
@adamsilverstein as you see in my gif above the first click gave correct feedback about the plugin being installed but for the continuous clicks the button do not update automatically.

But the actual process behind the scenes seems to be working because if you refresh the screen the continuous updates/installs have then been made. So I just think it's about getting the feedback to the user working, and then of course it might be even better with a update/queued notice at the top as you've already implemented on plugins.php.

**Comment by adamsilverstein** [comment]
@j-falk Aha, right. Ok, I have this fixed in https://github.com/obenland/shiny-updates/pull/35

**Comment by j-falk** [comment]
@adamsilverstein great! I tested and seems to work perfect when you only install new plugins but when I mix it with also updating an existing plugin on that screen it freezes:
![untitled gif 2](https://cloud.githubusercontent.com/assets/1665833/12079171/dbfc56d0-b22f-11e5-9d24-b1397c94f3a7.gif)

Probably connected to this javascript error?
![screenshot 2016 01 03 at 15 33 07](https://cloud.githubusercontent.com/assets/1665833/12079172/e07c4a58-b22f-11e5-8e08-15e88ab79899.png)

What do you think about the actions after you've clicked the button, wouldn't it be great if you could cancel an install/update that you have queued? I am thinking maybe a subtle x to the right in to button that would cancel the update/install?
![add plugins shiny updates wordpress](https://cloud.githubusercontent.com/assets/1665833/12079256/8f3c5676-b232-11e5-8339-dd122b64f9a0.png)

Also I guess the next step after installing a plugin would be to activate it, so in a way it would make sense that the button changed to a button to activate the plugin. But that brings up the question on how to handle a lot of setup screens that get initiated after activating plugins like woocommerce or buddypress, which I think was a big topic the last time when the initial parts of shiny updates were introduced in 4.2.

**Comment by j-falk** [comment]
Another very small comment, maybe remove the ! in the button after successful installation?
![add plugins shiny updates wordpress](https://cloud.githubusercontent.com/assets/1665833/12079374/c095b89e-b236-11e5-963a-d01f9613b258.png)

I personally don't use ! too often and I am not sure how often that is used otherwise in WordPress right now?

**Comment by adamsilverstein** [comment]
Thanks for the feedback!  The console error you found should be resolved? Are you testing the branch? I'll make sure I pushed latest.

**Comment by obenland** [comment]
I think we agreed that clicking the update/install buttons directly works just as well as selecting certain plugins and then run a bulk action on them.
