### ISSUE TITLE
Accessibility Team Review

### ISSUE THREAD

**Issue by AdamSoucie** [obenland/shiny-updates#129]
*Creating this thread for the WP a11y team to drop any issues we find in here and keep them organized*

**Comment by AdamSoucie** [comment]
Use of ARIA on the "Update" button is inconsistent.  The "Update" button always uses "Update" for the text, but only updates for plugins have include an "aria-label" value.

For example, Akismet has a button text of "Update" and an ARIA label value of "Update Akismet now".  This is a great feature as it makes the button's action more clear, but the additional information is not present for Core, Themes, and the "Update All" button.

**Comment by swissspidy** [comment]
Thanks for opening this thread!

> Use of ARIA on the "Update" button is inconsistent. […]

Is this across the board or especially on the `update-core.php` page? Of course I'll go through the whole code to fix things, but it'd be good to know where to start 😃

**Comment by AdamSoucie** [comment]
Only in update-core.php from what I've seen so far

**Comment by swissspidy** [comment]
It seems like we use `wp.a11.speak` very inconsistently so far. Would be great to have your feedback on this as well.

**Comment by swissspidy** [comment]
#171 fixes the aria labels

**Comment by RachelRVasquez** [comment]
Hi there, hopping on this thread as well. I wanted to mention the links that use hashes in their href attributes in functions.php like this one, `<a href="#" class="close-full-overlay"><span class="screen-reader-text"><?php _e( 'Close' ); ?></span></a>`. It looks like there are a lot of links that use hashes and are actually for triggering an action instead of directing the user to another page. We can improve accessibility/semantics in these cases by converting them to button elements instead which are natively accessible and will not disorient screen reader users due to the hashes.

````
<button class="close-full-overlay"><span class="screen-reader-text"><?php _e( 'Close' ); ?></span></button>
```.
