### ISSUE TITLE
Update All button icon while updating needs a new color

### ISSUE THREAD

**Issue by mapk** [obenland/shiny-updates#157]
The 'Update All' button in update-core.php needs a new icon color when the updates are happening after it's been clicked.

![screen shot 2016-05-25 at 3 47 38 pm](https://cloud.githubusercontent.com/assets/617986/15558679/b2ba3400-2290-11e6-996b-72e8546ca104.png)

After clicking the 'Update All' blue button, it assumes the updating status like the other buttons and shows the updating icon spinning around. This is fine, but that orange looks pretty bad against that blue.

Possible Solutions:

1. If we show the spinning icon, it should be white when it's on a blue button.
2. We don't show this stage for this button. This means after clicking 'Update All', the button should just switch to a disabled state while everything is being updated.
3. Leave it as is. Not my favorite choice. :)

**Comment by swissspidy** [comment]
#156 suggests just removing the icon.

#132 suggests completely changing the UI, e.g. with one big spinner / progress bar / whatever on top of the whole table.

**Comment by afragen** [comment]
FYI, a different admin color scheme changes this button's default color. You will have to override this to change.

**Comment by afragen** [comment]
#161 suggests removing default admin color as fix for changing button color.

**Comment by afragen** [comment]
> After clicking the 'Update All' blue button, it assumes the updating status like the other buttons and shows the updating icon spinning around. This is fine, but that orange looks pretty bad against that blue.

> Possible Solutions:

> 1. If we show the spinning icon, it should be white when it's on a blue button.
> 2. We don't show this stage for this button. This means after clicking 'Update All', the button should just switch to a disabled state while everything is being updated.
> 3. Leave it as is. Not my favorite choice. :)

@swissspidy wants to move the design discussion back here, so back we are.

I would propose a 4th solution.

Change the overall style of the 'Update All' button on this page so that instead of a filled in button with the user's selected admin color scheme. We use a normal button that has the outline of the user's selected admin color scheme. Currently, no other button changes with an AJAX action. Since we're creating this new button action, why shouldn't we create a new standard for how this type of button appears?

Current state
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/15654982/93824936-264d-11e6-91ca-c06241e19990.png)

Proposed state
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/15654995/a79e29b2-264d-11e6-9b79-85b01d41ace3.png) ![screenshot_03](https://cloud.githubusercontent.com/assets/1296790/15655042/0d22a592-264e-11e6-9cc6-36445c6d32ab.png)

The obvious advantage of this proposal is that the spinner looks good. The disadvantage is that it would change the usual default look for the default button on this page. This is the PR in #161

**Comment by mapk** [comment]
I just commented on #161 but it goes along with this discussion as well.
https://github.com/obenland/shiny-updates/pull/161#issuecomment-222405412

**Comment by afragen** [comment]
Solved(?) with https://github.com/obenland/shiny-updates/pull/174/commits/38cdb1bc51e6b40db2a19d7520b72633b5435ddd in #174
