### ISSUE TITLE
Failed update flow

### ISSUE THREAD

**Issue by Clorith** [obenland/shiny-updates#201]
Currently when an update fails, an error notification is added as an admin notice.

This forces you to notice the failure message ,then look over your plugins to find the failed one, this up and down, let's call it motion, is probably not the best we can do.

I have two thoughts on potential better alternatives;

1. Add the plugin name to the failure notification
2. Add the notification to the plugin row it relates to

The benefit to having it at the top is of course that a long list of plugins means you might not see every row, so option 1 is probably the optimal one

Quick by-thought, but if the list of updates is long, do we scroll-to-top when you click "update all" so that they actually have the admin notice area in view during the updates?

**Comment by swissspidy** [comment]
Hey there 👋 

Are you talking about `update-core.php` or another page? Because on `plugins.php`, both your suggestions are actually implemented. There you'll see a notification for each plugin row and 1 notice at the top. When there's an error, it scrolls to the top (see #163) to show a notice holding all errors.

**Comment by rosswintle** [comment]
I agree that this needs work. I don't like the notices at all.

The `update-core.php` page does not show plugin names in notices. I just tested this with an up-to-date clone from GitHub in case it was recently added. You just get:

`Update Failed: Plugin update failed.`

If there's multiple failures this looks particularly odd:

https://cloudup.com/cwJsWXtSop7

And it's worse in action because they are dynamically added and make the screen jump around when you're probably scrolling to see what failed.

The GIF linked below is a simulation of an case where connection from the web server to wordpress.org it lost and multiple updates fail. It results in the screen jumping all over the place in a situation where things are failing and the user may be panicking.

https://cloudup.com/cREb_hUwlXv

It would also be good, if possible, to get more information about failures when they happen. A network connection fault has a very different resolution to a file permissions problem. I’d like to see more information about why an update failed, even if it’s tucked away behind a “more details” link or something.

**Comment by rosswintle** [comment]
Just discovered this when a plugin install fails. This is MUCH better. It's inline with the plugin that failed, has a more detailed description of what went wrong, and suggests what the user can do next. Could failure notices on `update-core.php` look like this too?:

![inline plugin fail](https://cldup.com/KIc2DzZmby.png)

**Comment by rosswintle** [comment]
This, from `plugins.php`, is also an improvement on the multiple notices without plugin names. I would say that the mimumum we should do to improve the `update-core.php` experience is to use this as the notice format:

![plugins.php multiple failure notice](https://cldup.com/kOGXC1uOmC.png)

**Comment by swissspidy** [comment]
> This, from `plugins.php`, is also an improvement on the multiple notices without plugin names. I would say that the mimumum we should do to improve the `update-core.php` experience is to use this as the notice format:

This is the notice I mentioned before. It's shown when there are errors during bulk updating plugins. Since we don't bulk update on `update-core.php` but update each item individually, we probably can't easily add such a combined notice there.

Even if we could, the screen would still jump at least once.

> It would also be good, if possible, to get more information about failures when they happen. A network connection fault has a very different resolution to a file permissions problem.

I agree that `Update Failed: Plugin update failed.` is not very helpful. I think we can simply swap out the error message here (as suggested by @Clorith) and I will look into this right now.

After that, we can further discuss this for sure.

**Comment by rosswintle** [comment]
Can't be hard to track a failure count, and update it on subsequent fails, can it? If you don't want to track the failure counts in JS then you can just stick a `data-` attribute on the notice to track it?

I want to have a go at patching this now...but don't have time. Maybe later.

**Comment by swissspidy** [comment]
> Can't be hard to track a failure count, and update it on subsequent fails, can it?

We do that already 😉 I was thinking about implementing it without looking more closely at the code though. Plus it could look weird swapping a single notice with a bulk notice when there's more than 1 error.

**Comment by rosswintle** [comment]
Start with a bulk notice then, as you do on `plugins.php`. Start with `1 Failure` and update it as subsequent failures come in.

Just had a peer into `wp.updates.updateItemError`. This needs me to understand more about how you guys do accessibility and translation in JS. Might have to leave it to you experts.

**Comment by Clorith** [comment]
Wow, I look away for a few minutes and suddenly it's 4 hours and 8 replies later.

I don't mind multiple failure notifications in `update-core.php`, if they reference what plugin they relate to so you know what you are looking at (from a power user perspective). I can then dismiss them individually as I look into each failure, but that's what I'd like, and may not make as much sense to the average user of course.

**Comment by obenland** [comment]
Update-core related changes were not approved for merge, closing.
