### ISSUE TITLE
FTP credentials form: No error feedback on plugins.php

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#206]
update-core.php (and themes.php):

![update-core](https://cloud.githubusercontent.com/assets/617637/15776337/3a726474-2987-11e6-8ead-9df8df33b138.gif)

plugins.php:
![plugins](https://cloud.githubusercontent.com/assets/617637/15776352/488ffb34-2987-11e6-857c-9333170c704b.gif)

**Comment by swissspidy** [comment]
Apparently that "Connection Information" title is sometimes an `<h1>` and sometimes an `<h2>`. I don't even…

**Comment by ocean90** [comment]
Right, `request_filesystem_credentials()` contains:

```php
// Print a H1 heading in the FTP credentials modal dialog, default is a H2.
$heading_tag = 'h2';
if ( 'plugins.php' === $pagenow || 'plugin-install.php' === $pagenow ) {
	$heading_tag = 'h1';
}
echo "<$heading_tag id='request-filesystem-credentials-title'>" . __( 'Connection Information' ) . "</$heading_tag>";
```

Does this still make sense? Probably not for the modal.

cc: @afercia

**Comment by afercia** [comment]
Ideally, when a modal dialog opens it should be the only "visible" content for screen readers. This is implemented in part thanks to the `role="dialog"`, in part thanks to the fact we constrain tabbing within the modal (TL:DR we should also implement a couple more things). 
Since, when open, it's the only available content, it make sense to use a `h1`. Alternatively, use no heading at all like in this example that uses a `div`... https://www.marcozehe.de/2015/02/05/advanced-aria-tip-2-accessible-modal-dialogs/ but we always need a "title" to use as target for `aria-labelledby`. 
I'd say a `h2` wouldn't make much sense.

**Comment by afercia** [comment]
Ah! The `h2` was used for the FTP credentials form when displayed in `update-core.php`, see:
<img width="517" alt="screen shot 2016-06-03 at 19 14 20" src="https://cloud.githubusercontent.com/assets/1682452/15786963/a596008e-29bf-11e6-8d72-fa09d14c02a3.png">

So, not sure if the `h2` is still needed. Maybe you're going to always use the modal? If so, what about no-js?
