### ISSUE TITLE
Deactivation not allowed from Add Plugin

### ISSUE THREAD

**Issue by jeffmcneill** [obenland/shiny-updates#255]
From the Add Plugin area it allows to install and activate but not deactivate or remove? Should be able to at least deactivate if can activate from the add plugin screen. 

Also, for Network plugins, Activation should be Network Activation.

**Comment by swissspidy** [comment]
_Plugins -> Add New_ is all about 1 action: Installing a new plugin. After installing a plugin, it's very likely that you want to activate it. That's why we added that "Activate" button after a few discussions.

If you want to delete or deactivate your plugins, there's a solid plugins list table at _Plugins -> Installed Plugins_ that you can use for that.

There a bunch of discussions about this activation flow, see #64 and [the relevant core ticket](https://core.trac.wordpress.org/ticket/31002). Especially this feedback there:

> Activate seems like it could work, not convinced about deactivate (since that's not really in the "install/make it work" vein). Would need to make sure we are clearly distinguishing between activate and install.
>
> One issue I could see in the future is if/when we introduce in-place installation - activate would probably still need to take you away from the page, so then we really are mixing things up on one screen.

I'm closing this issue as it's out of scope for shiny updates. We were proposing adding the currently available functionality to core and doing a code freeze while preparing a patch. Feel free to leave your thoughts on that core ticket though.

-----

> Also, for Network plugins, Activation should be Network Activation.

We have #254 to discuss this.

**Comment by jeffmcneill** [comment]
You can close, but from a user interaction perspective, a button that can be used to activate, should be able to deactivate. I believe the point is to provide more functionality within the Add Plugins page (hence the activation button), but there is no good reason not to have that button also allow deactivation, and it is no technical challenge. The idea that someone activates a plugin, and then might change their mind, there is no obvious place to go with Shiny Updates. Basically, the button leaves me hanging there. In the old system, at least on install one was ejected back to the plugins page, and they could activate, and on that same page, de-activate. That is no longer possible, since it was deemed bad interaction to get ejected back to plugins (and I agree with that).
