### ISSUE TITLE
Improve UX after core update is added to queue

### ISSUE THREAD

**Issue by ocean90** [obenland/shiny-updates#268]
![no-further-updates](https://cloud.githubusercontent.com/assets/617637/15854274/596b3f3e-2ca9-11e6-8950-888fe6c78e3e.gif)

* Clicked Update for bbPress
* bbPress update is running
* Clicked Update for core (while bbPress update is running)
* Clicked Update for Twenty Fifteen, Twenty Eleven and Bacgkround Image Cropper (while bbPress update is running), nothing happens.

Discussion: https://wordpress.slack.com/archives/feature-shinyupdates/p1465292663000160

* Should the buttons be disabled with a notice why they can't be used?
* The queue should be smarter: Push core update always to the end if it hasn't run yet.

#241/#247 popped up again and I don't think it's an enhancement anymore. It's a UX issue.

**Comment by swissspidy** [comment]
Current status:

* Core runs always at the end on "Update All". The spinner is shown right from the start though
* If core is running, all other buttons are disabled (including "Update All" and "Re-install Now")
* When the last item in the table is being updated, all other buttons are disabled as well

See aaronjorbin/develop.wordpress#5

Closing this for now.

**Comment by ocean90** [comment]
@swissspidy Somehow this made things worse. See the following gif:

![bulk](https://cloud.githubusercontent.com/assets/617637/16015561/8db6ab06-3196-11e6-99bf-584b594a0f3c.gif)

During the update of Hello Dolly I clicked the Update buttons for the themes but their status didn't change so I clicked them again.

**Comment by swissspidy** [comment]
Thanks for the update, @ocean90!

Not sure when exactly this was introduced, but swissspidy/develop.wordpress@2ff5f7f629eafcb4e6467acdca0e1eabf49f5789 makes sure an item can't be added to the queue multiple times.

Since update-core.php uses `wp.updates.updateItem` to add items to the queue, items only get processed if there's no other ajax request running (see `wp.updates.queueChecker`), hence no spinner.  That's different from other screens, where the update functions like `wp.updates.updatePlugin` are used directly.

I think the latter one is a bug and we should use the queue everywhere, but allow for parallel requests as well. @obenland  What do you think?

**Comment by obenland** [comment]
I'm not a big fan of swissspidy/develop.wordpress@2ff5f7f. I think we should handle it the same way we do it for Update All.

**Comment by obenland** [comment]
Should be fixed in https://github.com/swissspidy/develop.wordpress/commit/6a113d56cac787e21c98f365ca8c1a54e5499f82.

**Comment by swissspidy** [comment]
For the record, not adding things to the queue twice is important. Should have kept that :)

**Comment by obenland** [comment]
We do that in the handlers by checking if it has a class of `.updating-message`.
