### ISSUE TITLE
Handle error messages on plugin deletion

### ISSUE THREAD

**Issue by obenland** [obenland/shiny-updates#38]
Error messages on a failed deletion currently end up nowhere. There is no UI for it.

**Comment by mapk** [comment]
After our conversation, I believe we agreed to display a global msg after every deletion. So it might look something like this:

![global - deleted plugin confirmation](https://cloud.githubusercontent.com/assets/617986/12309440/92c35126-b9ff-11e5-8eaf-bd046d7f4e7d.png)

**Comment by obenland** [comment]
But only for bulk deletions, correct?

**Comment by mapk** [comment]
No, I think for all deletions. I understand the confirmation being the disappearance of the plugin from the list, but I think it would be clearer to have a confirmation msg for single deletions as well.

**Comment by obenland** [comment]
Comments has been working like that for years. I saw it as an opportunity to align experiences here.

**Comment by MichaelArestad** [comment]
This is interesting. Does the plugin disappear? If not, why do a global notification?

**Comment by mapk** [comment]
@MichaelArestad, the plugin does disappear once deleted. That's what @obenland is saying could be obvious enough instead of using a global msg.

I understand this being the case with comments but with plugins (things that actually affect the software), it might be nice for users to still get that global msg. Especially if users are troubleshooting things like site performance, etc.
