### ISSUE TITLE
UI hierarchy for update-core.php

### ISSUE THREAD

**Issue by MichaelArestad** [obenland/shiny-updates#5]
Here's an ultra quick stab at assembling a sort of hierarchy for the updates page. I did a tiny bit to start it on `add/cards`, but could use some help cardifying the other sections (a bit over my head).

![image](https://cloud.githubusercontent.com/assets/1123119/11572407/1c776b6a-99cf-11e5-9890-3873dab2aaca.png)

Ideally, there would be a new section below the notice containing the "Update all the things" button and potentially a list of what would be updated. I can do a quick mockup of this section.

Another thought is to use these to fold up the plugins and themes sections so the autoupdates wouldn't be buried so far down. 

![image](https://cloud.githubusercontent.com/assets/1123119/11572533/d5056588-99cf-11e5-8dd1-1b560a2bd2bb.png)

**Comment by MichaelArestad** [comment]
CC @adamsilverstein

**Comment by adamsilverstein** [comment]
Looks good. What do you think about removing the extra update button at the bottom of each section?

**Comment by MichaelArestad** [comment]
+1

**Comment by ocean90** [comment]
Has anyone already tried to unify this screen a bit? Basically the list from the readme at https://github.com/dd32/x67.

**Comment by adamsilverstein** [comment]
@ocean90 I have not heard that discussed, I like the concept of a unified layout. We are still brainstorming the approach for this page, thanks for the suggestion!

**Comment by MichaelArestad** [comment]
@ocean90 Yeah. @mapk and I will be investigating a much more unified/simplified version of this view.

**Comment by paaljoachim** [comment]
@MichaelArestad that sounds very interesting!
As right now that update page is a bit too cumbersome.

Here is a suggestion.
![dashboard-update-screen](https://cloud.githubusercontent.com/assets/5323259/12158009/79f25440-b4d6-11e5-97e2-31414465c39f.jpg)

**Comment by mapk** [comment]
I'm going to branch out here and question whether or not separating these updates is even necessary. Can we include them all in one single table list? While the explorations on this page are all definitely improvements, can we simplify it further?

I've comped something to look at with this thought.
![core updates v1](https://cloud.githubusercontent.com/assets/617986/12522896/40678de2-c108-11e5-9cc1-06b7fe968cbd.png)

1. Include all updates in one general list. In order for this to be scannable, there should probably be thumbnail images next to each update - this includes the Core update as well.
2. The table will have columns for the "Type" of update which can be sortable by 'most recent' or 'type' to group common types together.
3. Buttons are include in each row for individual updates which operate similarly to the Theme install screen where the buttons change depending on the action being performed.
4. The buttons 'update all' and 'update selected' are now prominent above the table.
5. The Automatic updates reside in their own table below. Once an item is automatically set to auto update, maybe that item gets removed from the table above. So if I select that I want plugins to automatically update, all plugin updates get removed from the main table.

**Comment by paaljoachim** [comment]
@mapk That sure looks nice and clean! It is uses less space and is right to the point. Very good clarity!
Very good job!..:)

**Comment by mapk** [comment]
* Smaller thumbnails
 * Tighter rows
 * Reverted the auto-updates back to original form but with white box behind it
 * Removed the lower buttons from table
 * Removed the bulk update options like the buttons and checkboxes

![core updates v2](https://cloud.githubusercontent.com/assets/617986/12598634/49eb0d7c-c440-11e5-8d63-4dfb0b329896.png)

**Comment by paaljoachim** [comment]
Awesome! Even better!

**Comment by obenland** [comment]
I like it a lot. I wonder if the list would stand out more if we made the two notices just description text and left the Automatic Updates section as it is now.

**Comment by mapk** [comment]
@obenland Is this what you were thinking?
![core updates v2a](https://cloud.githubusercontent.com/assets/617986/12599019/2a344086-c443-11e5-84bd-25318575820e.png)

**Comment by paaljoachim** [comment]
The autoupdates section: Could we have a general WP, plugins and themes icons and make it somewhat similar to the update section above it? Instead of having Update button to the right it could have an Auotomatic Update toogle.

**Comment by obenland** [comment]
> @obenland Is this what you were thinking?

Yes! How do you like it?

**Comment by obenland** [comment]
> Instead of having Update button to the right it could have an Automatic Update toggle.

I'm not sure we should encourage automatic updates on an individual level. It would be much more impactful if we get users to activate it for all plugins/themes etc.

Although, following my logic we should have just one checkbox to automatically update everything.

**Comment by mapk** [comment]
> Yes! How do you like it?

If we're not going to clean up the auto-updates section, then I'm OK leaving the it as is. Putting the white box behind it really highlighted the awkwardness of that section. At least the "save changes" button no longer looks like it could apply to the table above. That was my biggest worry.

**Comment by melchoyce** [comment]
Man, this is looking leagues better than the current update screen. Kudos.

Some overall suggestions: 

* "Check again" isn't using the most current header button styling (see: https://cloudup.com/cyvdQu7KTBJ)
* `Last checked on` might be better in italics
* Might want to check with @afercia about accessibility to see if it's okay to remove the table headings
* I think it would be more clear if the "sort" dropdown was aligned to the left of the table. I was really confused at first about how the dropdown was related to the column beneath it, since they seem to be grouped together
* Will sort need an "apply" button like the other list tables?
* Speaking of the descriptive text, they should either be continued on the same line, or actually be separate paragraphs with space in between them
* Moving "sort" over would also help with the weird illusion going on between the descriptive text above and the table below, where it looks like there's a much bigger gap than there actually is between the two
* I think the type of update is also confusing without the context of a table header. Might be worth exploring ways to make that more clear, either with a better label ("core update," "plugin update," etc.) or maybe even an icon?
* "Automatic updates" should be an h2 (https://cloudup.com/cLLgi37ulRb)

> If we're not going to clean up the auto-updates section, then I'm OK leaving the it as is. Putting the white box behind it really highlighted the awkwardness of that section.

+1

**Comment by afercia** [comment]
Please consider that for keyboard users and screen reader users navigation is a linearized process, so they would need to read all the list of updates before making a decision and then they should find the primary actions at the bottom. Like the "Update All" button should be repeated at the bottom.
Wouldn't be fair to force users to navigate backwards to the top :) The most expected workflow is a submit/primary action at the end of a form.

How is going to be marked up? Would be excellent if it wouldn't use a table in the first place ;)

**Comment by mapk** [comment]
@melchoyce thanks for your feedback! I've incorporated a lot of your points.
@afercia You insight on screen readers is super helpful. I've added a button to the bottom of the table, does that solve the issue?

![core updates v2a](https://cloud.githubusercontent.com/assets/617986/12656383/d4f720f4-c5b2-11e5-8e73-6c0ada37ce5e.png)

**Comment by obenland** [comment]
Do we need the Type column at all?

**Comment by mapk** [comment]
I personally would like to easily know whether something was a plugin or theme or a core software update. Does it need to be its own column, not really. But it should be scannable and obvious.

**Comment by afercia** [comment]
@mapk way better with the bottom button, thanks :)

**Comment by paaljoachim** [comment]
I really like the Type column as it give me exactly what kind of update it is. Moving the kind of update to another place well I guess that is possible as well.

**Comment by samuelsidler** [comment]
I think WordPress core needs to be called out a bit better. It's the most important "type" of any. I'd rather separate it out into a different section, instead of merely putting it on top of the list (which I assume is the intention).

As far as the type column, I'd say it can be removed if we can distinguish the type another way. Maybe it makes more sense to be at the beginning of the row? Or using an icon instead? I like the idea that I can filter for only theme or plugin updates and run those first (or last).

**Comment by obenland** [comment]
> I like the idea that I can filter for only theme or plugin updates and run those first (or last).

Your statement makes me actually question if we should have a sorter at all. Sorting and filtering are two different things, and frankly I don't see the benefit of either here. I think it's one more opportunity to reduce user confusion.

**Comment by obenland** [comment]
Can we say just "Type" instead of "Type of Update"?
Should the Update All buttons be primary?

**Comment by mapk** [comment]
> I'd rather separate it out into a different section, instead of merely putting it on top of the list (which I assume is the intention).

We can, but it should still follow this table format. I like including it among the other updates giving the user one place to focus on. I'm not entirely sure separating it out brings more focus to it, or causes more confusion. I also didn't intend for it to reside at the top always, but it can. :)

> Or using an icon instead?

Yes, I really like this idea, but didn't know if icons alone would relay the intended info correctly. How familiar are our users with the icons?

> Sorting and filtering are two different things, and frankly I don't see the benefit of either here.

I think sorting is good to have so that the user can group them by type. But that's me speculating what the user might want to do. I think our testing next week will help. By default I imagine the list sorting by most recent.

> Can we say just "Type" instead of "Type of Update"?

Yes

> Should the Update All buttons be primary?

Good question. Let's make them primary because that's the main CTA we want the user to perform.

**Comment by swissspidy** [comment]
> I think sorting is good to have so that the user can group them by type. But that's me speculating what the user might want to do. I think our testing next week will help. By default I imagine the list sorting by most recent.

I'm not sure you need to have it sorted by most recent. There's not even a date displayed. I'd rather have it grouped by type (getting rid of the type column) or just alphabetically.

> Should the Update All buttons be primary?

+1

**Comment by mapk** [comment]
> I'm not sure you need to have it sorted by most recent. There's not even a date displayed. 
Should we display a date then? People often like to update things a couple days after the release to make sure the bugs are worked out. Is this even an issue with WP plugins?

> I'd rather have it grouped by type (getting rid of the type column) or just alphabetically. 
The current display without 'Shiny Updates' displays them in groups. This took up a lot of space and brought some confusion into the page. Grouping them into one table helps focus the user to concentrate on one area for sifting through updates they can apply. I like the idea to show them as grouped by type when page loads, so should we offer the user the ability to then sort by 'A-Z', 'Z-A', 'Most recent'? Anything else?

**Comment by obenland** [comment]
We might be overthinking this. Why do we need sorting at all?

**Comment by swissspidy** [comment]
@obenland Absolutely.

Let's create an MVP of the table first and see how it works.

**Comment by mapk** [comment]
I'm down with that. Go for it.

**Comment by swissspidy** [comment]
I started working on this in a separate branch now, see f0bbc7e3ba232ba7a76a2a119aaf36282eb7188f. It uses `WP_List_Table` and hence is much easier to read and to extend. Here's a sneak peek:

<img width="1264" alt="screen shot 2016-04-29 at 23 04 19" src="https://cloud.githubusercontent.com/assets/841956/14929872/2b032952-0e60-11e6-9ef5-4bf2cc39a7d6.png">

A couple of things I noticed along the way:

* The `update-core.php` code is quite hacky and not flexible. The only real hook we can use to display the list table is `core_upgrade_preamble`, which runs at the very end of the page. It would be great if we could work on a patch for this page rather soon to test the flow properly.
 
* The update API does not return any image data for plugins, so unless there's a change to the API we can't really show the plugin's image. Unless we call the plugins API ourselves, of course.
* The core update message is more complex than one might think (see `core_upgrade_preamble()` and `list_core_update()`). It displays the new version _and_ the current one. You can either upgrade, re-install or download packages manually. Oh, and you can even dismiss an update! Not to forget about the PHP & MySQL compatibility checks.
 
 This is something that needs to be considered in the mockups. I have no problem with stripping out things like dismissing an update and turning some buttons into links, but everything should be well-conceived.
 
* What about translations?
 
 It's easy to list all the available translation updates in the table as well (see https://twitter.com/swissspidy/status/710419334162685952), but I understand that not everybody will like that idea. Especially since that would mean updating individual translations, which might not make that much sense.

**Comment by obenland** [comment]
Nice work @swissspidy!

I'm pretty sure the update API can be extended to include plugin icons going forward.

I think @ocean90 had an opinion about showing languages in that table.

**Comment by paaljoachim** [comment]
Very nice Pascal!
It seems very natural to also add translation updates to the same area.

**Comment by mapk** [comment]
If WordPress doesn't need an update, it probably shouldn't appear in the Update Table, correct? So where do these buttons (ignore the blue update button) reside when WordPress is not visible in the table?

<img width="997" alt="screen shot 2016-05-10 at 11 19 15" src="https://cloud.githubusercontent.com/assets/617986/15196737/b6a2055c-1782-11e6-8f3d-04f96d20e6dc.png">

We probably can't include the "Download Nightly Build" btn, or the "Re-install Now" btn, or the "Download 4.5.2" btn in the table row of WordPress because it's not relating to an UPDATE. So I'm thinking these buttons will need to continue to live outside the table.

Once a person has WordPress installed, I believe the average user is only concerned with updating it. So these buttons take on more of a back seat to the Update Table, so they should probably exist below the table.

Does this sound about right?

**Comment by obenland** [comment]
Should they exist at all? Are these things that 80% of users use/need?

**Comment by swissspidy** [comment]
Good question. I guess _it depends_.

Here's how it currently looks like when a en_US site is running the latest version of WordPress:

<img width="799" alt="screen shot 2016-05-11 at 23 25 11" src="https://cloud.githubusercontent.com/assets/841956/15197077/ca05490e-17cf-11e6-825a-d1f4de9ec1b7.png">

That's not much information and probably not of great help when displayed inside the table.

---

For a locale site it looks like this:

<img width="1080" alt="screen shot 2016-05-11 at 23 24 48" src="https://cloud.githubusercontent.com/assets/841956/15197086/d279a800-17cf-11e6-9a3c-30a07b7f326e.png">

The buttons read: re-install, download, dismiss update

That's a lot more, with three call-to-action buttons. In the current form, this makes sense to display in the table.

---

Note: There's a ticket on trac about getting rid of the download button, and perhaps others too. See https://core.trac.wordpress.org/ticket/36811

---

There have been some discussions in the past that WordPress shouldn't really show the current version number because it's not that relevant. That means we could theoretically get rid of showing anything at all if there's no update.

On the other hand, "Re-install" is a legit option in cases where an update wasn't 100% successful. No idea why it's only shown for locale sites though.

If that option is displayed outside the table, but an available update is displayed inside the table, that sounds a bit confusing actually.

**Comment by mapk** [comment]
> On the other hand, "Re-install" is a legit option in cases where an update wasn't 100% successful. No idea why it's only shown for locale sites though.
If that option is displayed outside the table, but an available update is displayed inside the table, that sounds a bit confusing actually.

I think "Re-install" is something completely different from an "Update" (outside of a serious update error). If there's an instance where the update failed, shouldn't we display the msg in an error notification in the same row as the WordPress update, similarly to how we do the Plugins?

> Should they exist at all? Are these things that 80% of users use/need?

I don't think any buttons that call for "downloading" should exist inside the Update table. For that matter, they shouldn't exist on the _WordPress Updates page_ either. I'm all for removing those completely.

**Comment by swissspidy** [comment]
> I think "Re-install" is something completely different from an "Update" (outside of a serious update error). 

It's an important part of the `update-core.php` page though. If you have a suggestion for how it should look like with this information outside the table, I'm all for it.

> If there's an instance where the update failed, shouldn't we display the msg in an error notification in the same row as the WordPress update, similarly to how we do the Plugins?

It's not about immediately failed updates with shiny updates. It's for cases where maybe one file wasn't modified 100% correctly (mostly because of file permissions) and an error popping up a few hours later (i.e. function not found or something like that). When someone posts this in the support forums, the solution often is to just click 'Re-install Now'. Or perhaps they modified some core files and want a clean state again.

----

I'm for removing the download buttons / links, but keeping the re-install button for now.

**Comment by swissspidy** [comment]
Closing in favour of #116.
