### ISSUE TITLE
Bulk plugin updates notifications

### ISSUE THREAD

**Issue by obenland** [obenland/shiny-updates#7]
I think we need design help to come up with a better way to display notifications for bulk plugin updates.
(And bulk theme updates in Multisite)

**Comment by adamsilverstein** [comment]
That would be great! And bulk site upgrades in multisite!

**Comment by adamsilverstein** [comment]
Here is a screencast my latest iteration on progress updates for bulk updates:

![screencast](http://cl.ly/3Q3q0b453H3X/Screen%20Recording%202015-12-23%20at%2002.46%20PM.gif)

**Comment by MichaelArestad** [comment]
Just recapping some brainstorming we did earlier.

Instead of multiple notices, there would be just one. Something like this:

![image](https://cloud.githubusercontent.com/assets/1123119/11989799/63f1fb2a-a9c1-11e5-910f-aa1112cfd389.png)

![image](https://cloud.githubusercontent.com/assets/1123119/11989801/6e72a450-a9c1-11e5-9112-dfcb6e0456cd.png)

![image](https://cloud.githubusercontent.com/assets/1123119/11989804/7774f5f8-a9c1-11e5-8f03-059a76af4ae6.png)

These were pretty quickly put together to convey the idea. I'd like to have a spinner and probably refine the copy. There would be a way to expand it into something like this:

![image](https://cloud.githubusercontent.com/assets/1123119/11989821/a2a17b3e-a9c1-11e5-948f-cf80272999eb.png)

I'm debating on just showing the list of every plugin queued for update, though with a color change to indicate the ones that haven't started yet. I don't think we need the bullets and instead can show a green checkmark noticon next to each plugin updated successfully.

On completion, the notice would go from blue to green or red depending on success. Maybe a yellow if one of the plugins had an issue.

**Comment by adamsilverstein** [comment]
@MichaelArestad 
Making some progress here, maybe close to ready for your help :)

Here is what I have in the `features/bulk-update-notifications` branch:

![screencast](http://cl.ly/3B1A111m3C2u/Screen%20Recording%202015-12-24%20at%2002.34%20PM.gif)

**Comment by MichaelArestad** [comment]
Rad. Was just looking at it now.

**Comment by j-falk** [comment]
@adamsilverstein a thought, shouldn't the notification show both if you initiate the bulk update through the Bulk Actions drop-down or if you initiate them one by one by clicking on the update plugin link in the plugin list. Right now these two workflows who accomplish the same thing, updating multiple plugins, are 2 different experiences.

Updating multiple plugins through Bulk Actions drop-down:
![untitled gif 3](https://cloud.githubusercontent.com/assets/1665833/12079341/59d28c0a-b235-11e5-9852-f7df1023c62f.gif)

Updating multiple plugins through clicking update plugin links in plugin list:
![untitled gif 4](https://cloud.githubusercontent.com/assets/1665833/12079351/d04957d8-b235-11e5-9e94-93b69d9946c9.gif)

**Comment by mapk** [comment]
I really like the compactness @MichaelArestad was working toward and that @adamsilverstein began to implement. But I also liked the clear separation between each of the updates, so I just thought to refine on the idea a bit in these comps. Basically each line in the 'show details' view is dedicated to a specific update. So it cycles through 'updating' text, then swaps out to show 'success' or 'failure'.

Minified notification.
![bulk notifications - hide details](https://cloud.githubusercontent.com/assets/617986/12155221/ecf781bc-b478-11e5-861e-e395eace30db.png)

Viewing details.
![bulk notifications - show details](https://cloud.githubusercontent.com/assets/617986/12155227/fc11d7e2-b478-11e5-87fc-ef3a273fd529.png)

I tried to explore the idea of adding a rotating 'update' icon in there for a visual indicator that it's working behind the scenes. Also used varying color to indicate status.

**Comment by obenland** [comment]
How important is it to have detailed feedback about the result of individual plugins, over the current notification, that just says "Selected plugins updated|activated|deleted".

**Comment by mapk** [comment]
I've been thinking about that too. Do we need to show the details, or do we do that because we've been doing it already? We seem to handle all these notifications in the plugin list already, right? I guess my question might even go a bit further... do we even need any sort of notification at the top?

Maybe we can just clean up the notifications in the plugins list below.

**Comment by obenland** [comment]
> do we do that because we've been doing it already?

We've only been doing it in the plugin. Core currently doesn't.
Be creative, don't let yourself be influenced what's already there, chances are it was not created deliberately or it's out of date. I'd love to see what you think notifications should _ideally_ look like.

**Comment by mapk** [comment]
With the idea of dropping the disconnected notifications at the top of the page, I created this comp. The concept is to keep the notifications integrated with each plugin, but in their own column for easy visual scanning.

![update-notifications](https://cloud.githubusercontent.com/assets/617986/12184455/2ab39b40-b54a-11e5-9419-7a85672e86c4.png)

The premise is that the SUCCESS notifications would disappear after a few seconds on their own leaving nothing to be displayed in that column. 

The UDPATE button would only show if an update was available. 

The UPDATING notification could be a progress bar giving the user a more accurate indication as to the time involved in the update process. I think this would be more helpful than a spinning gif or an ellipses. 

The ERROR notifications would remain displayed until resolved in addition to the background being a light red. 

I also added thumbnails of the plugins in the comp seeing as that's been a frequent request. 

I'd love to hear some feedback.

**Comment by obenland** [comment]
In-row notifications about response statuses is an interesting challenge in this project. :)

I think we could get away with only adding the column if there are updates available. Installs happen somewhere else, and if we delete a plugin we remove the row (Unless that fails. We'll need to think about a post-delete notification placement too at some point). If we end up doing shiny (de)activations, the visual feedback could just be the added or removed background highlight.

It's probably not going to be feasible to do a progress bar for the simple reason that we don't know how long it takes to update a specific plugin, and we also don't report back to the browser where we are in the update process. I wouldn't mind to continue using the rotating arrows here.

For failed updates notification I'm missing more information about why the update failed. In the current state users could just hit that Retry link indefinitely, never knowing what the issue is with us not giving them something to google a solution for.

**Comment by adamsilverstein** [comment]
@mapk Nice mockup, I like the direction. I agree with all of @obenland's comments as well. 

For failures, how about adding a 'Details' link next to 'Retry' that expands an area showing the failure details that are returned as part of the ajax response?

**Comment by mapk** [comment]
These are excellent comments and very helpful!

@obenland, I understand the 'wasted' column argument when there are no updates, so I'm exploring how to resolve this.

@adamsilverstein, that's a great idea!

**Comment by obenland** [comment]
> I understand the 'wasted' column argument when there are no updates, so I'm exploring how to resolve this.

Maybe it would make sense to continue going down the path of adding a row, like the existing update notification does? Not sure what the best solution is here. @MichaelArestad, do you have any opinions?

**Comment by mapk** [comment]
Before jumping back into the in-row notifications and seeing if that can be worked out more, I wanted to try something completely different. I believe this is very clear, obvious, and understandable for the user and might not have as many technical limitations as my earlier comp.

I got the idea from how we treat a row when the plugin is deleted. The row highlights in red, then disappears. So I'm taking that idea and applying it to the other actions. I'm not completely sold on this, but wanted to present it to the group.

Keep in mind that the user will most likely not see all these colors at one time on the screen, but it's displayed this way to account for the varying scenarios.

![in-row notifications v4](https://cloud.githubusercontent.com/assets/617986/12207742/3862e3fa-b5fd-11e5-9031-a8abba39bcf3.png)

The SUCCESS message would fade away after a second, so the green would only be briefly visible.

These would only work with the assumption that the user would not need to interact with the plugin itself during these stages because the overlay would block them from doing so.

**Comment by mapk** [comment]
> Maybe it would make sense to continue going down the path of adding a row, like the existing update notification does?

This could work if it doesn't get lost visually. I'll try an idea around this.

**Comment by mapk** [comment]
@obenland, this might be more inline with what you're thinking?

![in-row notifications v5](https://cloud.githubusercontent.com/assets/617986/12208513/0b71ac8c-b602-11e5-9aff-f7093baccf3b.png)

I was initially worried they wouldn't be visible enough, but that might have been based on the current way the updates were being displayed. I think after changing background colors, they stand out better, but are still not overbearing.

**Comment by MichaelArestad** [comment]
Jumping in again here. I would make sure there's at least some notification at the top with status updates. Even if they're super simple like `Updating 3 plugins`, `Updates complete`, etc. Failures probably also need to be represented at the top. I think the top notifications can be pretty simple and accompany the inline notifications.

The top of page will very likely be in view since the apply button is there. Often a plugin that is being updated is not visible on the screen. With smaller devices, this is especially the case so we need to make sure some visual indicator is at the top to show the user feedback on their action

As far as the design, I'm the above two mockup inline notices don't feel like they're a part of the same design ecosystem. Part of that is because we don't do anything quite like that, though I believe Hugo proposed something similar at some point. I don't think they'll fly primarily for contrast a11y reasons.

I'd take another stab at it. The checkboxes could probably also be hidden until the updates are complete meaning you could do something with that space. I would see if you could combine the update action with the notification.

If we're looking at inline notices to accompany the top notice (totally on board with this idea), we need to consider how they might look in other places in WordPress. It is inevitable that a plugin might hijack this pattern and use it with less care than we might give it.

That said, here are a few iterations on them: https://cloudup.com/imRFxzqi3Gx

These are probably the closest to WordPress styling and feels closer to the buttons styles.

![image](https://cloud.githubusercontent.com/assets/1123119/12213834/4c3170dc-b63d-11e5-9268-dd6c231d1a88.png)

![image](https://cloud.githubusercontent.com/assets/1123119/12213922/fb7f4ae4-b63f-11e5-93fc-558c6603e8cb.png)

![image](https://cloud.githubusercontent.com/assets/1123119/12213941/99322504-b640-11e5-9f51-d24ed8228e6a.png)

![image](https://cloud.githubusercontent.com/assets/1123119/12213946/a0d2660c-b640-11e5-9a8e-d8d577884de7.png)

**Comment by mapk** [comment]
While still working out some of the design on the in-row notifications, here are some ideas for how the global notifications might work.

Minified Mixed Messages
![global - multiple failed plugins - minified v1](https://cloud.githubusercontent.com/assets/617986/12250617/40a685da-b87d-11e5-90db-6b4b9a2b0431.png)

Extended Mixed Messages
![global - multiple failed plugins - expanded v1](https://cloud.githubusercontent.com/assets/617986/12250620/451bc346-b87d-11e5-9bb8-ad7f0bf2208f.png)

This would only apply to error messages and nothing else. All other message details would remain in-row.

**Comment by mapk** [comment]
Thinking through some of @MichaelArestad's suggestions, I've built another comp displaying the in-row notifications similarly as I did above but without the colorful backgrounds. I wanted to be careful that these in-row notifications were quickly seen, so I think they needed to stand out a bit still from the general styling. I used some additional design tactics to achieve this, also with the thought of tieing them in nicely with the Global notifications at the very top.

1. The notification extends almost full width of the plugin similarly to the Global notifications. This provides visual weight to distinguish it from the plugin content.
2. The notification retains a color bar on the left side depending on the type of notification similarly to the global notifications in the above comment. This helps the msg stand out and quickly relates visually the type.
3. The error msg has a button for 'retry' which follows the current styling of other buttons. 

![in-row notifications v5c](https://cloud.githubusercontent.com/assets/617986/12251186/a7a9d652-b881-11e5-87f5-cacf3b43bcd1.png)

I think the styling is closer to the echosystem, but refined in the right places to make it something consistent, obvious, and nice to looks at. :)

**Comment by obenland** [comment]
I like where this is headed.

> Extended Mixed Global Messages

Where do the "View Plugin" links point to?
I think it would be easiest if we could keep all that information in one admin notice with a yellow border, what do you think?

> in-row notifications

I love having those in the description cell, rather than having us add an entire row every time. I wish Shiny Updates v1 did it that way. We have to be aware that this will break backwards compatibility though. Not a necessarily a blocker in my opinion, but we should be deliberate about that and maybe get Helen's opinion on it as well.

@helenhousandi, what do you think?

**Comment by mapk** [comment]
> Where do the "View Plugin" links point to?
I think it would be easiest if we could keep all that information in one admin notice with a yellow border, what do you think?

Initially I thought it would link to the plugin and jump the user down on the page, but I agree with your concerns. Let's keep the error messaging right there in the global msg. What should it say in the in-row msg then? "Update failed.... [retry button]"?

> I love having those in the description cell, rather than having us add an entire row every time.

I was concerned this wouldn't be obvious enough at first though. But it appears to stand out quite well.

**Comment by mapk** [comment]
Based on some feedback from our chat meeting on Tuesday, here's a new comp.

![in-row notifications v5d](https://cloud.githubusercontent.com/assets/617986/12302847/339aae38-b9dc-11e5-9ff3-e651ae2ddef7.png)

1. I removed the text color in notifications to allow for better contrast.
2. I worked in the 'update' option and placed it on an active plugin to see what the notification looks like against a light blue background.
3. I kept the all caps in the brief part of the textual msg. I believe the little wording is fine to read in all caps and it helps separate it from the rest of the plugin.

I think we're pretty dang close with these further changes.

**Comment by helenhousandi** [comment]
My strong preference would be to stay away from all-caps - there isn't much of this in core and where it does exist it's not very pleasant or cohesive, I find it difficult to read despite being short text (and I do not have any text processing difficulties), and it feels very shouty for something that you might not really need to focus on.

**Comment by mapk** [comment]
Alright, I'll concede to the majority here and remove the all caps. :)  No worries. I love the feedback!

**Comment by obenland** [comment]
What about prepending those notices and have them be at the top of the cell rather than at the bottom?

**Comment by mapk** [comment]
I'm so used to seeing it the other way, this feels a bit odd. They do line up nicely with the title and links to the left though. I'm impartial right now. Let me sit on it for a day.

As I'm looking, they do take on more priority in the cell now which is a good thing.

**Comment by adamsilverstein** [comment]
I like @obenland's suggestion: it lines up a bit more pleasantly and its a bit more noticeable in that spot.

**Comment by mapk** [comment]
Also just realized the way we handle the update msg for active plugins. We change the background color of that plugin to orange and the left border as well. I like that.

**Comment by mapk** [comment]
Taking into account the difference of the row color (orange) when needing an update, and the visuals from the Theme notification (yellow), I thought to rework the styling some more.

![in-row notifications v6e](https://cloud.githubusercontent.com/assets/617986/12336215/2b284094-bab8-11e5-873a-0a49c81645eb.png)

1. I removed the blue row background color from the active plugins, but left the blue left border. This allows the notifications to pop/standout a bit better. 
2. I used the same yellow color from the Theme update notifications with this plugin. 
3. I kept the CTA as a button, and used the branding 'orange' color which jives nicely with the yellow background. My concern here is it might be too shocking, but maybe that's a good thing being that it's the CTA.
4. All other notifications retain the grey background color. Is this OK?

**Comment by mapk** [comment]
Based off some further discussion with @obenland, here's a comp with colored backgrounds on the notifications.

![in-row notifications v6f](https://cloud.githubusercontent.com/assets/617986/12368987/228d8a54-bba6-11e5-8660-34e5015f1689.png)

**Comment by MichaelArestad** [comment]
That button looks wild with that orange. I'd probably not use it since it's not like anything else in the admin. I'm wondering if we can't just have a text link. (mostly because I'm not sure the other button styles will look great either)

I might also remove the mirrored warning border for plugins with updates available. The border has a specific context of being active (with a border) or inactive. The use of it starts to get murky with that border there. For example, if a plugin is inactive and has an update, it won't be clear what its status is.

Why is the Details link floated right on the update available notice?

**Comment by mapk** [comment]
@MichaelArestad - 
1. I agree about the button. If we have to resort to making it a link (I'm not a fan of that) we can. I think links are easily lost, and being that it's the main CTA, I believe users would identify and be more likely to click it as a button.
2. So would the mirrored border just remain blue? I wouldn't remove it if it's an active plugin, right? But maybe just keep it blue?
3. Details link to flush right b/c I'm keeping the actions that one would perform within a in-row notification grouped together. This makes it much more smoother for a user to move the cursor to only one area to interact.

**Comment by swissspidy** [comment]
See #110.

Any progress in this regard?

**Comment by obenland** [comment]
I think we should keep it the way it is for now.

**Comment by swissspidy** [comment]
Alright, thanks. Closing for now.
